## Copyright (c) 2020 Arseniy Kuznetsov
##
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.


[Sample-Router]
    # for specific configuration on the router level, change here the defaults values from below
    hostname = 192.168.88.1

[default]
    dhcp = True
    dhcp_lease = True
    use_ssl = False
    lte = False
    public_ip = True
    queue = True
    dns = False
    pool = True
    ssl_certificate_verify = False
    routing_stats = False
    capsman_clients = False
    plaintext_login = True
    wireless_clients = False
    bfd = False
    interface = True
    eoip = False
    neighbor = True
    health = True
    bgp = False
    ipv6_route = False
    kid_control_assigned = False
    use_comments_over_names = True
    ipsec = False
    gre = False
    ipv6_neighbor = False
    enabled = True
    ipv6_firewall = False
    check_for_updates = False
    user = True
    installed_packages = True
    ipv6_pool = False
    monitor = True
    connection_stats = False
    netwatch = True
    wireless = False
    switch_port = False
    poe = False
    connections = True
    certificate = False
    capsman = False
    route = True
    kid_control_dynamic = False
    firewall = True
    ipip = False
    no_ssl_certificate = False
    hostname = localhost
    username = mktxp_user
    password = 9l6627DMFamM
    remote_dhcp_entry = None
    remote_capsman_entry = None
    port = 8728
